// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUj83X8-ZOtxYB5QCCgZyrsr-u059w8aM',
    appId: '1:771008721734:web:0f830d9815b7c20f6b2b47',
    messagingSenderId: '771008721734',
    projectId: 'petsnapmx',
    authDomain: 'petsnapmx.firebaseapp.com',
    storageBucket: 'petsnapmx.appspot.com',
    measurementId: 'G-HGP22Z8ZKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNb7iqjdTxRYWSH9PsjUp8u1DJZa96i1o',
    appId: '1:771008721734:android:fed7aedc6c66dd396b2b47',
    messagingSenderId: '771008721734',
    projectId: 'petsnapmx',
    storageBucket: 'petsnapmx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIpUnOTC3yRfe2XWR0RuBCvcvZQ9kaUU',
    appId: '1:771008721734:ios:33e44971dfab5cd86b2b47',
    messagingSenderId: '771008721734',
    projectId: 'petsnapmx',
    storageBucket: 'petsnapmx.appspot.com',
    iosClientId: '771008721734-oe7du63vrup0gkoderj6m2bga5rokvoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIpUnOTC3yRfe2XWR0RuBCvcvZQ9kaUU',
    appId: '1:771008721734:ios:33e44971dfab5cd86b2b47',
    messagingSenderId: '771008721734',
    projectId: 'petsnapmx',
    storageBucket: 'petsnapmx.appspot.com',
    iosClientId: '771008721734-oe7du63vrup0gkoderj6m2bga5rokvoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
